---

- name: Install sinopia
  npm: name=sinopia global=true version={{ sinopia_version }}

- name: Create sinopia group
  group: name={{ sinopia_user }}

- name: Create sinopia user
  user: name={{ sinopia_user }} group={{ sinopia_user }} system=yes

- name: Create config directory
  file: path={{ sinopia_config }} state=directory owner={{ sinopia_user }} group={{ sinopia_user }}

- name: Create data directory
  file: path={{ sinopia_storage }} state=directory owner={{ sinopia_user }} group={{ sinopia_user }}

- name: Create log directory
  file: path={{ sinopia_log }} state=directory owner={{ sinopia_user }} group={{ sinopia_user }}

- name: Copy configuration
  template: src=config.yaml dest={{ sinopia_config }}/config.yaml owner={{ sinopia_user }} group={{ sinopia_user }}
  notify: restart sinopia

- name: Copy NPM users
  template: src=users dest={{ sinopia_config }}/users owner={{ sinopia_user }} group={{ sinopia_user }}
  when: sinopia_manage_users

- name: Copy server conf
  template: src=nginx dest=/etc/nginx/sites-available/sinopia owner={{ sinopia_user }} group={{ sinopia_user }}
  notify: restart nginx

- name: Enable server
  file: src=/etc/nginx/sites-available/sinopia dest=/etc/nginx/sites-enabled/sinopia state=link owner={{ sinopia_user }} group={{ sinopia_user }}

- name: Copy Daemon script
  template: src=daemon dest=/etc/init.d/sinopia  mode=0755
  notify: restart sinopia

- name: Update rc sinopia
  shell: update-rc.d -f sinopia defaults

- name: Start Sinopia
  service: name=sinopia state=started enabled=yes
